name: Research Software Engineering

plugins:
  - jekyll-datapage-generator

page_gen:
- data: events
  template: event
  dir: events
  index_files: false
  name_expr: record['title'] + "-" + Date.parse(record['date']).strftime("%d-%m-%Y")
  title: title
  extension: md
  filter_condition: Date.parse(record['date']).strftime("%s").to_i > Time.now.to_i

collections:
  team:
    output: true
  projects:
    output: true
  events:
    output: true